# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket      = "ssita"
    credentials = "/home/wlados/.gcp/terraform.json"
    prefix      = "terraform/geo_terragrunt"
  }
}
