---

## for DB instance
- name: DB
  hosts: db
  become_method: sudo
  remote_user: wlad1324
  vars:
    ansible_ssh_private_key_file: /home/wlados/.aws/ssh_centos/id_rsa

  roles:
     - SSITA_geocitizen_DB_gcp

...
